name: Compile
on:
  workflow_dispatch:
  push:
    paths: .github/workflows/compile.yml
jobs:
  build: 
    runs-on: ubuntu-22.04
    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 2048
          temp-reserve-mb: 1
          swap-size-mb: 1
          remove-dotnet: true
          remove-android: true
          remove-haskell: true
          remove-codeql: true
          remove-docker-images: true
      - name: Checkout
        uses: actions/checkout@v4
      - name: Prepare
        run: | 
          sudo apt update
          sudo apt install $(cat dependencies) -y
          git clone https://github.com/coolsnowwolf/lede.git openwrt
          cp diffconfig openwrt
          mkdir output
      - name: Compile
        run: | 
          cd openwrt
          ./scripts/feeds update -a 
          ./scripts/feeds install -a
          cp diffconfig .config
          make defconfig
          make download -j$(nproc)
          make -j$(nproc)
          rm -rf ./bin/targets/*/*/packages
          cp bin/targets/*/*/* ../output
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: output
          retention-days: 90
